name: post_repository
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  jsonplaceholder_api:
    path: ../jsonplaceholder_api

dev_dependencies:
  mocktail: ^0.1.0
  test: ^1.16.4