# This workflow builds two artifacts for the Flutter Project, one Android and one iOS
name: Build
on:
  create:
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android App Bundle
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v1.5.0
        with:
          channel: stable
      - run: flutter doctor -v

      - name: Setup Melos
        run: |
          dart pub global activate melos
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Checkout project code
        uses: actions/checkout@v2

      - run: |
          melos bootstrap
          melos run generate-i10n

      - name: Build App Bundle
        run: flutter build appbundle

      - name: Upload App Bundles
        uses: actions/upload-artifact@v2
        with:
          name: android-bundle
          path: build/app/outputs/bundle/release/app-release.aab
  build-ios:
    name: Build iOS Bundle
    runs-on: macos-10.15
    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v1.5.0
        with:
          channel: stable
      - run: flutter doctor -v

      - name: Setup Melos
        run: |
          dart pub global activate melos
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Checkout project code
        uses: actions/checkout@v2

      - run: |
          melos bootstrap
          melos run generate-i10n

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Upload iOS App Bundle
        uses: actions/upload-artifact@v2
        with:
          name: ios-bundle
          path: build/ios/iphoneos/
