# This workflow runs all tests in this Flutter Project
# this includes all tests in the app project, as well as tests in local packages if any (via melos)
# It also checks for dart analyze issues and code formatting, but will not fail on error
name: Tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    name: Unit and widget tests
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v1.5.0
        with:
          channel: stable
      - run: flutter doctor -v

      - name: Checkout project code
        uses: actions/checkout@v2

      - name: Setup Melos
        run: |
          dart pub global activate melos
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - run: |
          melos bootstrap
          melos run generate-i10n
          
      - name: (No fail) Analyze code
        run: melos run analyze
        continue-on-error: true
        
      - name: (No fail) Check code formatting
        run: melos run check-formatting
        continue-on-error: true
      
      - name: Run Flutter tests
        run: melos run test

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
